// 多语言数据包 - 流浪狗救助，15位活动发起人，完整字段（含联系邮箱标签）
const langData = {
    zh: {
        badgeTemp: "⚠️ 紧急救助",
        badgeGroup: "民间志愿团体 · 无政府资金",
        mainTitle: "寒冬救助：为受伤流浪狗筹集医疗与口粮",
        p1: "📸 等待治疗的狗狗",
        p2: "📸 饥寒交迫的流浪狗",
        p3: "📸 救助站的日常",
        storyTitle: "🐾 流浪狗的艰难求生",
        storyP1: "在中国，流浪狗的数量庞大。它们大多是被主人遗弃，或者出生在街头。没有固定的食物来源，每天在垃圾堆里寻找残羹剩饭；没有遮风挡雨的家，冬天只能蜷缩在墙角发抖，夏天忍受蚊虫叮咬。很多狗狗因为交通事故或被虐待而受伤，骨折、皮肤病、眼病十分常见。由于没有动物保护法，它们得不到任何政府救助。",
        storyP2: "我们是一群普通的年轻人，只是这次募捐活动的发起人。我们利用业余时间联系兽医、寻找合适的救助站、组织志愿者排班。我们本身并不直接承担全部费用，而是通过发起这个募捐活动，向社会爱心人士筹集流浪狗的医疗费和口粮。我们负责让每一笔捐款都公开透明，确保送到最需要帮助的流浪狗身上。",
        storyP3: "每一只被救助的狗狗都会得到治疗、绝育和疫苗，然后努力为它们寻找领养家庭。您的每一笔捐款，无论多少，都会直接用于购买药品、狗粮、支付手术费。我们会在社交媒体上定期公开账目和救助进度。请帮帮这些可怜的毛孩子，让它们有机会重新奔跑、被爱。",
        useT1: "🍖 日常口粮",
        useP1: "每天需要消耗大量狗粮。30元就能买一袋普通狗粮，够一只中型犬吃一周。",
        useT2: "🏥 医疗救治",
        useP2: "每只受伤狗狗的平均治疗费用约300元。50元可以支付一次驱虫药或疫苗。",
        allocTitle: "📊 资金分配计划",
        alloc1: "45% 医疗手术与药物",
        alloc2: "30% 购买狗粮与营养品",
        alloc3: "15% 犬舍维护与保暖",
        alloc4: "10% 救助车辆油费",
        targetLbl: "链上实时目标：4,500 USDT",
        liveStatus: "🔴 区块链实时同步 · 每一笔入账公开可查",
        payTitle: "🔪 一起帮助流浪狗",
        paySub: "填写下方信息，选择国际安全通道。我们将定期公布资金使用明细。",
        lblEmail: "您的邮箱（用于发送救助报告）",
        lblNotes: "留言 / 给狗狗的一句话",
        btnMoonPay: "通过安全网关捐助",
        btnDirect: "我已转账USDT",
        directLbl: "直接转入USDT（ERC20）至我们唯一钱包",
        wechatErr: "微信支付暂未开放，请使用MoonPay或USDT直捐。",
        percentSuffix: "已筹集",
        ackTitle: "💎 活动发起人 · 聚沙成塔",
        contactEmailLabel: "📧 联系邮箱：",

        ackName1: "陈宇轩", ackJob1: "软件工程师", ackMotto1: "「代码能改变世界，善意也能。」",
        ackName2: "林雨桐", ackJob2: "宠物医生", ackMotto2: "「每一次缝合，都是一次重生。」",
        ackName3: "王浩泽", ackJob3: "大学生志愿者", ackMotto3: "「年轻的热血，应该流在最需要的地方。」",
        ackName4: "赵思敏", ackJob4: "会计师", ackMotto4: "「每一笔捐款都是信任，必须清清楚楚。」",
        ackName5: "刘子昂", ackJob5: "供应链主管", ackMotto5: "「让每一斤狗粮都准时到达。」",
        ackName6: "周小琪", ackJob6: "平面设计师", ackMotto6: "「设计可以温柔，生命必须坚强。」",
        ackName7: "林益晨", ackJob7: "自由摄影师", ackMotto7: "「拍完照，顺手帮狗狗擦擦眼睛。」",
        ackName8: "陈航轩", ackJob8: "咖啡师", ackMotto8: "「下班后把店里的咖啡渣拿去铺狗舍除味。」",
        ackName9: "何子睿", ackJob9: "游戏策划", ackMotto9: "「策划虚拟世界，也想拯救真实生命。」",
        ackName10: "周澄", ackJob10: "健身教练", ackMotto10: "「撸铁之外，也要给流浪狗一点力量。」",
        ackName11: "陆一鸣", ackJob11: "烘焙师", ackMotto11: "「揉面团的手，也可以帮狗狗梳毛。」",
        ackName12: "吴一凡", ackJob12: "动画师", ackMotto12: "「每一帧动画都很慢，但救狗不能慢。」",
        ackName13: "苏晚晴", ackJob13: "花艺师", ackMotto13: "「包扎花束，也包扎过流浪狗的伤口。」",
        ackName14: "夏晚宁", ackJob14: "插画师", ackMotto14: "「画板上是色彩，救助站是温度。」",
        ackName15: "宋悠然", ackJob15: "品牌策划", ackMotto15: "「帮流浪狗讲个好故事，才能被领养。」"
    },
    en: {
        badgeTemp: "⚠️ Emergency Rescue",
        badgeGroup: "Grassroots · No Government Funding",
        mainTitle: "Winter Relief: Raising Funds for Injured Stray Dogs",
        p1: "📸 Dogs waiting for treatment",
        p2: "📸 Hungry and cold strays",
        p3: "📸 Daily life at the shelter",
        storyTitle: "🐾 The Harsh Struggle of Stray Dogs",
        storyP1: "In China, there are millions of stray dogs. Most were abandoned by their owners or born on the streets. They have no steady food source, scavenging in trash bins; no shelter from freezing winters or burning summers. Many suffer from fractures, skin diseases, or eye infections due to accidents or abuse. With no animal protection law, they receive no government help.",
        storyP2: "We are a group of young initiators of this fundraising campaign. We use our spare time to contact veterinarians, find suitable shelters, and organize volunteer shifts. We don't bear all the costs ourselves. Instead, by launching this campaign, we raise funds from caring people for the medical treatment and food of stray dogs. We ensure every donation is transparent and reaches the dogs in greatest need.",
        storyP3: "Every rescued dog receives medical care, sterilization, vaccines, and then we try to find them a loving home. Your donation, no matter the size, will go directly to medicine, dog food, and surgery fees. We regularly post financial reports on social media. Please help these poor souls have a second chance at life.",
        useT1: "🍖 Daily Dog Food",
        useP1: "$5 can buy a bag of dry food that feeds a medium dog for a week.",
        useT2: "🏥 Medical Care",
        useP2: "Average treatment cost per injured dog is around $10. $2 can buy a deworming pill.",
        allocTitle: "📊 Fund Allocation",
        alloc1: "45% Medical Treatment & Medicine",
        alloc2: "30% Dog Food & Nutrition",
        alloc3: "15% Shelter Maintenance & Heating",
        alloc4: "10% Transport Costs",
        targetLbl: "Live On‑Chain Goal: 4,500 USDT",
        liveStatus: "🔴 Blockchain Synced – Every Transaction Public",
        payTitle: "🔪 Help Stray Dogs",
        paySub: "Fill out the form to choose a secure payment method. We will publish fund usage reports regularly.",
        lblEmail: "Your Email (to receive rescue updates)",
        lblNotes: "Message for the dogs",
        btnMoonPay: "Donate via Secure Gateway",
        btnDirect: "I have transferred USDT",
        directLbl: "Send USDT (ERC20) directly to our wallet",
        wechatErr: "WeChat Pay not available. Please use MoonPay or direct USDT.",
        percentSuffix: "Raised",
        ackTitle: "💎 Campaign Initiators · Many Hands Make Light Work",
        contactEmailLabel: "📧 Contact Email:",

        ackName1: "Yuxuan Chen", ackJob1: "Software Engineer", ackMotto1: "「Code changes the world, so does kindness.」",
        ackName2: "Yutong Lin", ackJob2: "Veterinarian", ackMotto2: "「Every suture is a rebirth.」",
        ackName3: "Haoze Wang", ackJob3: "Student Volunteer", ackMotto3: "「Young passion should flow where it's most needed.」",
        ackName4: "Simin Zhao", ackJob4: "Accountant", ackMotto4: "「Every donation is trust, must be crystal clear.」",
        ackName5: "Ziang Liu", ackJob5: "Supply Chain Manager", ackMotto5: "「Every pound of dog food arrives on time.」",
        ackName6: "Xiaoqi Zhou", ackJob6: "Graphic Designer", ackMotto6: "「Design can be gentle, life must be strong.」",
        ackName7: "Yichen Lin", ackJob7: "Freelance Photographer", ackMotto7: "「After taking photos, I wipe the dogs' eyes.」",
        ackName8: "Hangxuan Chen", ackJob8: "Barista", ackMotto8: "「After work, I use coffee grounds to deodorize the kennel.」",
        ackName9: "Zirui He", ackJob9: "Game Designer", ackMotto9: "「Designing virtual worlds, also want to save real lives.」",
        ackName10: "Cheng Zhou", ackJob10: "Fitness Coach", ackMotto10: "「Besides lifting iron, give some strength to stray dogs.」",
        ackName11: "Yiming Lu", ackJob11: "Baker", ackMotto11: "「Hands that knead dough can also brush dogs' fur.」",
        ackName12: "Yifan Wu", ackJob12: "Animator", ackMotto12: "「Every frame is slow, but saving dogs can't be slow.」",
        ackName13: "Wanqing Su", ackJob13: "Florist", ackMotto13: "「Bouquet wrapping, and also bandaging stray dogs' wounds.」",
        ackName14: "Wanning Xia", ackJob14: "Illustrator", ackMotto14: "「Palette is color, shelter is warmth.」",
        ackName15: "Youran Song", ackJob15: "Brand Planner", ackMotto15: "「Tell a good story for stray dogs, then they can be adopted.」"
    },
    es: {
        badgeTemp: "⚠️ Rescate de emergencia",
        badgeGroup: "Grupo civil · Sin fondos gubernamentales",
        mainTitle: "Ayuda invernal: recaudando fondos para perros callejeros heridos",
        p1: "📸 Perros esperando tratamiento",
        p2: "📸 Vagabundos hambrientos y con frío",
        p3: "📸 Día a día en el refugio",
        storyTitle: "🐾 La dura lucha de los perros callejeros",
        storyP1: "En China hay millones de perros callejeros. La mayoría fueron abandonados por sus dueños o nacieron en la calle. No tienen fuente fija de alimento, rebuscando en basureros; no tienen refugio contra inviernos helados o veranos ardientes. Muchos sufren fracturas, enfermedades de la piel o infecciones oculares debido a accidentes o maltrato. Sin una ley de protección animal, no reciben ayuda gubernamental.",
        storyP2: "Somos un grupo de jóvenes iniciadores de esta campaña de recaudación. Usamos nuestro tiempo libre para contactar veterinarios, encontrar refugios adecuados y organizar turnos de voluntarios. No asumimos todos los costos nosotros mismos. En cambio, lanzando esta campaña, recaudamos fondos de personas solidarias para el tratamiento médico y la comida de los perros callejeros. Nos aseguramos de que cada donación sea transparente y llegue a los perros que más lo necesitan.",
        storyP3: "Cada perro rescatado recibe atención médica, esterilización, vacunas y luego intentamos encontrarle un hogar amoroso. Su donación, sin importar el tamaño, irá directamente a medicinas, comida para perros y cirugías. Publicamos informes financieros regularmente en redes sociales. Por favor, ayude a estas pobres almas a tener una segunda oportunidad.",
        useT1: "🍖 Comida diaria",
        useP1: "$5 puede comprar una bolsa de comida seca que alimenta a un perro mediano por una semana.",
        useT2: "🏥 Atención médica",
        useP2: "El costo promedio de tratamiento por perro herido es de unos $10. $2 pueden comprar una pastilla desparasitante.",
        allocTitle: "📊 Asignación de fondos",
        alloc1: "45% Tratamiento médico y medicinas",
        alloc2: "30% Comida y nutrición",
        alloc3: "15% Mantenimiento y calefacción del refugio",
        alloc4: "10% Costos de transporte",
        targetLbl: "Objetivo en cadena: 4.500 USDT",
        liveStatus: "🔴 Sincronizado con blockchain – cada transacción pública",
        payTitle: "🔪 Ayuda a perros callejeros",
        paySub: "Complete el formulario para elegir un método de pago seguro. Publicaremos informes de uso de fondos regularmente.",
        lblEmail: "Su correo (para recibir actualizaciones de rescate)",
        lblNotes: "Mensaje para los perros",
        btnMoonPay: "Done a través de pasarela segura",
        btnDirect: "He transferido USDT",
        directLbl: "Envíe USDT (ERC20) directamente a nuestra billetera",
        wechatErr: "WeChat Pay no disponible. Use MoonPay o USDT directo.",
        percentSuffix: "Recaudado",
        ackTitle: "💎 Iniciadores de la campaña · Un granito de arena",
        contactEmailLabel: "📧 Correo de contacto:",

        ackName1: "Yuxuan Chen", ackJob1: "Ingeniero de software", ackMotto1: "«El código cambia el mundo, la bondad también.»",
        ackName2: "Yutong Lin", ackJob2: "Veterinaria", ackMotto2: "«Cada sutura es un renacimiento.»",
        ackName3: "Haoze Wang", ackJob3: "Voluntario universitario", ackMotto3: "«La juventud debe fluir donde más se necesita.»",
        ackName4: "Simin Zhao", ackJob4: "Contadora", ackMotto4: "«Cada donación es confianza, debe ser transparente.»",
        ackName5: "Ziang Liu", ackJob5: "Gerente de logística", ackMotto5: "«Cada kilo de comida llega a tiempo.»",
        ackName6: "Xiaoqi Zhou", ackJob6: "Diseñadora gráfica", ackMotto6: "«El diseño puede ser suave, la vida debe ser fuerte.»",
        ackName7: "Yichen Lin", ackJob7: "Fotógrafo independiente", ackMotto7: "«Después de tomar fotos, limpio los ojos de los perros.»",
        ackName8: "Hangxuan Chen", ackJob8: "Barista", ackMotto8: "«Después del trabajo, uso el poso de café para desodorizar las perreras.»",
        ackName9: "Zirui He", ackJob9: "Diseñador de juegos", ackMotto9: "«Diseñando mundos virtuales, también quiero salvar vidas reales.»",
        ackName10: "Cheng Zhou", ackJob10: "Entrenador físico", ackMotto10: "«Además de levantar pesas, da un poco de fuerza a los perros callejeros.»",
        ackName11: "Yiming Lu", ackJob11: "Panadero", ackMotto11: "«Las manos que amasan masa también pueden cepillar el pelo de los perros.»",
        ackName12: "Yifan Wu", ackJob12: "Animador", ackMotto12: "«Cada cuadro es lento, pero salvar perros no puede ser lento.»",
        ackName13: "Wanqing Su", ackJob13: "Florista", ackMotto13: "«Envolviendo ramos, también vendando heridas de perros callejeros.»",
        ackName14: "Wanning Xia", ackJob14: "Ilustradora", ackMotto14: "«La paleta es color, el refugio es calidez.»",
        ackName15: "Youran Song", ackJob15: "Planificadora de marca", ackMotto15: "«Cuenta una buena historia para los perros callejeros, entonces podrán ser adoptados.»"
    },
    ja: {
        badgeTemp: "⚠️ 緊急救助",
        badgeGroup: "民間ボランティア・政府資金なし",
        mainTitle: "冬の救助：負傷した野良犬のための医療費と食料を集める",
        p1: "📸 治療を待つ犬たち",
        p2: "📸 空腹と寒さに耐える野良犬",
        p3: "📸 保護施設の日常",
        storyTitle: "🐾 野良犬の過酷な生存",
        storyP1: "中国には何百万もの野良犬がいます。ほとんどは飼い主に捨てられるか、路上で生まれました。安定した食物源はなく、ゴミ箱をあさり、凍える冬や灼熱の夏をしのぐ避難所もありません。事故や虐待により骨折、皮膚病、眼病を患うことがよくあります。動物保護法がないため、政府の助けはありません。",
        storyP2: "私たちはこの募金活動の発起人である若者のグループです。余暇を利用して獣医師に連絡し、適切なシェルターを見つけ、ボランティアのシフトを組織します。私たち自身がすべての費用を負担するわけではありません。代わりに、このキャンペーンを通じて、野良犬の医療と食料のための資金を思いやりのある人々から集めます。すべての寄付が透明であり、最も必要としている犬に届くようにします。",
        storyP3: "救助された犬は皆、治療、不妊手術、ワクチンを受け、その後愛情ある家庭を見つけるよう努めます。あなたの寄付は、直接薬、ドッグフード、手術費に使われます。定期的にソーシャルメディアで資金報告を公開します。どうかこれらの哀れな命に第二のチャンスを与えてください。",
        useT1: "🍖 毎日のドッグフード",
        useP1: "5ドルで中型犬の1週間分のドライフードが買えます。",
        useT2: "🏥 医療ケア",
        useP2: "負傷犬の平均治療費は約10ドル。2ドルで駆虫薬が買えます。",
        allocTitle: "📊 資金配分",
        alloc1: "45% 医療治療と薬",
        alloc2: "30% ドッグフードと栄養",
        alloc3: "15% 施設維持と暖房",
        alloc4: "10% 交通費",
        targetLbl: "オンチェーン目標: 4,500 USDT",
        liveStatus: "🔴 ブロックチェーン同期 – 全取引公開",
        payTitle: "🔪 野良犬を助ける",
        paySub: "フォームに記入し、安全な支払い方法を選択してください。定期的に資金使用報告を公開します。",
        lblEmail: "メールアドレス（救助の最新情報を受信）",
        lblNotes: "犬へのメッセージ",
        btnMoonPay: "安全なゲートウェイで寄付",
        btnDirect: "USDTを送金しました",
        directLbl: "USDT (ERC20) を直接このウォレットに送ってください",
        wechatErr: "WeChat Payは利用できません。MoonPayまたは直接USDTをお使いください。",
        percentSuffix: "調達済み",
        ackTitle: "💎 活動発起人 · 積小成多",
        contactEmailLabel: "📧 連絡用メール：",

        ackName1: "Yuxuan Chen", ackJob1: "ソフトウェアエンジニア", ackMotto1: "「コードは世界を変える、優しさもまた。」",
        ackName2: "Yutong Lin", ackJob2: "獣医師", ackMotto2: "「すべての縫合は再生です。」",
        ackName3: "Haoze Wang", ackJob3: "ボランティア学生", ackMotto3: "「若い情熱は最も必要とされる場所に注ぐべきだ。」",
        ackName4: "Simin Zhao", ackJob4: "会計士", ackMotto4: "「すべての寄付は信頼です。明確でなければなりません。」",
        ackName5: "Ziang Liu", ackJob5: "サプライチェーン責任者", ackMotto5: "「すべてのドッグフードが時間通りに届くように。」",
        ackName6: "Xiaoqi Zhou", ackJob6: "グラフィックデザイナー", ackMotto6: "「デザインは優しく、命は強く。」",
        ackName7: "Yichen Lin", ackJob7: "フリーランス写真家", ackMotto7: "「写真を撮った後、犬の目を拭いてあげる。」",
        ackName8: "Hangxuan Chen", ackJob8: "バリスタ", ackMotto8: "「仕事帰りにコーヒーかすを犬舎の消臭に使う。」",
        ackName9: "Zirui He", ackJob9: "ゲームデザイナー", ackMotto9: "「仮想世界を企画しながら、現実の命も救いたい。」",
        ackName10: "Cheng Zhou", ackJob10: "フィットネスコーチ", ackMotto10: "「筋トレの合間に、野良犬にも力を。」",
        ackName11: "Yiming Lu", ackJob11: "パン職人", ackMotto11: "「こねる手で、犬の毛をとかすことも。」",
        ackName12: "Yifan Wu", ackJob12: "アニメーター", ackMotto12: "「一コマ一コマは遅いが、犬を救うのは遅くできない。」",
        ackName13: "Wanqing Su", ackJob13: "フローリスト", ackMotto13: "「花束を包む手で、野良犬の傷も包む。」",
        ackName14: "Wanning Xia", ackJob14: "イラストレーター", ackMotto14: "「パレットは色彩、シェルターは温もり。」",
        ackName15: "Youran Song", ackJob15: "ブランドプランナー", ackMotto15: "「野良犬に良いストーリーを語れば、引き取られるチャンスが増える。」"
    },
    ko: {
        badgeTemp: "⚠️ 긴급 구조",
        badgeGroup: "민간 자원봉사 · 정부 지원 없음",
        mainTitle: "겨울 구호: 다친 유기견을 위한 의료비와 사료 모금",
        p1: "📸 치료를 기다리는 개들",
        p2: "📸 굶주리고 추운 유기견들",
        p3: "📸 보호소의 일상",
        storyTitle: "🐾 유기견의 힘겨운 생존",
        storyP1: "중국에는 수백만 마리의 유기견이 있습니다. 대부분 주인에게 버려지거나 길거리에서 태어났습니다. 안정된 먹이가 없어 쓰레기통을 뒤지고, 얼어붙은 겨울이나 뜨거운 여름을 피할 피난처도 없습니다. 사고나 학대로 골절, 피부병, 안구 질환을 앓는 경우가 많습니다. 동물보호법이 없어 정부의 도움을 받지 못합니다.",
        storyP2: "우리는 이 모금 활동의 발기인인 젊은 그룹입니다. 여가 시간을 이용해 수의사에게 연락하고 적절한 보호소를 찾으며 자원봉사자 일정을 조직합니다. 우리가 모든 비용을 직접 부담하지는 않습니다. 대신 이 캠페인을 통해 유기견의 의료와 사료를 위한 기금을 따뜻한 마음을 가진 사람들로부터 모금합니다. 모든 기부가 투명하게 이루어지고 가장 필요로 하는 개들에게 전달되도록 합니다.",
        storyP3: "구조된 개는 모두 치료, 중성화 수술, 예방접종을 받고 사랑하는 가정을 찾도록 노력합니다. 귀하의 기부는 약, 사료, 수술비로 직접 사용됩니다. 정기적으로 소셜 미디어에 자금 사용 보고서를 게시합니다. 이 불쌍한 영혼들에게 두 번째 기회를 주세요.",
        useT1: "🍖 일일 사료",
        useP1: "5달러로 중형견 일주일치 건사료를 살 수 있습니다.",
        useT2: "🏥 의료 치료",
        useP2: "다친 개당 평균 치료비는 약 10달러입니다. 2달러로 구충제를 살 수 있습니다.",
        allocTitle: "📊 자금 배분",
        alloc1: "45% 의료 치료 및 약품",
        alloc2: "30% 사료 및 영양제",
        alloc3: "15% 보호소 유지 및 난방",
        alloc4: "10% 교통비",
        targetLbl: "온체인 목표: 4,500 USDT",
        liveStatus: "🔴 블록체인 동기화 – 모든 거래 공개",
        payTitle: "🔪 유기견 돕기",
        paySub: "양식을 작성하여 안전한 결제 수단을 선택하세요. 정기적으로 자금 사용 보고서를 게시합니다.",
        lblEmail: "이메일 (구조 업데이트 수신)",
        lblNotes: "개에게 보내는 메시지",
        btnMoonPay: "안전한 게이트웨이로 기부",
        btnDirect: "USDT를 송금했습니다",
        directLbl: "USDT (ERC20)를 이 지갑으로 직접 보내주세요",
        wechatErr: "WeChat Pay를 사용할 수 없습니다. MoonPay 또는 직접 USDT를 이용하세요.",
        percentSuffix: "모금됨",
        ackTitle: "💎 활동 발기인 · 작은 힘을 모아",
        contactEmailLabel: "📧 연락처 이메일:",

        ackName1: "Yuxuan Chen", ackJob1: "소프트웨어 엔지니어", ackMotto1: "「코드는 세상을 바꾸고, 친절도 마찬가지다。」",
        ackName2: "Yutong Lin", ackJob2: "수의사", ackMotto2: "「모든 봉합은 재생이다。」",
        ackName3: "Haoze Wang", ackJob3: "대학생 자원봉사자", ackMotto3: "「젊은 열정은 가장 필요한 곳에 흘러야 한다。」",
        ackName4: "Simin Zhao", ackJob4: "회계사", ackMotto4: "「모든 기부는 신뢰다, 명확해야 한다。」",
        ackName5: "Ziang Liu", ackJob5: "물류 관리자", ackMotto5: "「모든 사료가 제때 도착하도록。」",
        ackName6: "Xiaoqi Zhou", ackJob6: "그래픽 디자이너", ackMotto6: "「디자인은 부드러울 수 있지만, 생명은 강해야 한다。」",
        ackName7: "Yichen Lin", ackJob7: "프리랜서 사진가", ackMotto7: "「사진 찍고 나서, 개 눈가를 닦아준다。」",
        ackName8: "Hangxuan Chen", ackJob8: "바리스타", ackMotto8: "「퇴근 후 커피 찌꺼기로 개집 냄새를 제거한다。」",
        ackName9: "Zirui He", ackJob9: "게임 기획자", ackMotto9: "「가상 세계를 기획하면서, 실제 생명도 구하고 싶다。」",
        ackName10: "Cheng Zhou", ackJob10: "피트니스 코치", ackMotto10: "「운동 외에도 유기견에게 힘을 주자。」",
        ackName11: "Yiming Lu", ackJob11: "제빵사", ackMotto11: "「반죽하는 손으로 개 털도 빗겨줄 수 있다。」",
        ackName12: "Yifan Wu", ackJob12: "애니메이터", ackMotto12: "「한 프레임 한 프레임은 느리지만, 개 구하는 건 느릴 수 없다。」",
        ackName13: "Wanqing Su", ackJob13: "플로리스트", ackMotto13: "「꽃다발을 포장하는 손으로 유기견의 상처도 감싼다。」",
        ackName14: "Wanning Xia", ackJob14: "일러스트레이터", ackMotto14: "「팔레트는 색채, 보호소는 온기。」",
        ackName15: "Youran Song", ackJob15: "브랜드 플래너", ackMotto15: "「유기견에게 좋은 이야기를 들려주면 입양될 기회가 생긴다。」"
    },
    fr: {
        badgeTemp: "⚠️ Sauvetage d'urgence",
        badgeGroup: "Groupe bénévole · Aucun financement public",
        mainTitle: "Secours hivernal : collecte de fonds pour chiens errants blessés",
        p1: "📸 Chiens attendant des soins",
        p2: "📸 Errants affamés et gelés",
        p3: "📸 Vie quotidienne au refuge",
        storyTitle: "🐾 La dure lutte des chiens errants",
        storyP1: "En Chine, des millions de chiens errants vivent dans les rues. La plupart ont été abandonnés par leurs propriétaires ou sont nés dans la rue. Ils n'ont pas de source de nourriture fixe, fouillent les poubelles, et n'ont aucun abri contre les hivers glacials ou les étés brûlants. Beaucoup souffrent de fractures, de maladies de peau ou d'infections oculaires suite à des accidents ou de la maltraitance. Sans loi sur la protection animale, ils ne reçoivent aucune aide gouvernementale.",
        storyP2: "Nous sommes un groupe de jeunes initiateurs de cette campagne de collecte de fonds. Nous utilisons notre temps libre pour contacter des vétérinaires, trouver des refuges adaptés et organiser des plannings de bénévolat. Nous ne supportons pas tous les coûts nous-mêmes. Au lieu de cela, en lançant cette campagne, nous collectons des fonds auprès de personnes bienveillantes pour les soins médicaux et la nourriture des chiens errants. Nous veillons à ce que chaque don soit transparent et parvienne aux chiens qui en ont le plus besoin.",
        storyP3: "Chaque chien que nous sauvons reçoit des soins médicaux, une stérilisation, des vaccins, puis nous essayons de lui trouver un foyer aimant. Votre don, quel qu'en soit le montant, ira directement aux médicaments, à la nourriture pour chiens et aux frais chirurgicaux. Nous publions régulièrement des rapports financiers sur les réseaux sociaux. Aidez ces pauvres âmes à avoir une seconde chance.",
        useT1: "🍖 Nourriture quotidienne",
        useP1: "5 $ peuvent acheter un sac de croquettes qui nourrit un chien de taille moyenne pendant une semaine.",
        useT2: "🏥 Soins médicaux",
        useP2: "Le coût moyen du traitement par chien blessé est d'environ 10 $. 2 $ peuvent acheter un comprimé vermifuge.",
        allocTitle: "📊 Répartition des fonds",
        alloc1: "45% Traitements médicaux et médicaments",
        alloc2: "30% Nourriture et nutrition",
        alloc3: "15% Entretien et chauffage du refuge",
        alloc4: "10% Frais de transport",
        targetLbl: "Objectif on-chain : 4 500 USDT",
        liveStatus: "🔴 Synchronisé blockchain – toutes transactions publiques",
        payTitle: "🔪 Aidez les chiens errants",
        paySub: "Remplissez le formulaire pour choisir un moyen de paiement sécurisé. Nous publierons régulièrement des rapports d'utilisation des fonds.",
        lblEmail: "Votre email (pour recevoir des nouvelles des sauvetages)",
        lblNotes: "Message pour les chiens",
        btnMoonPay: "Donner via une passerelle sécurisée",
        btnDirect: "J'ai transféré des USDT",
        directLbl: "Envoyez USDT (ERC20) directement à notre portefeuille",
        wechatErr: "WeChat Pay indisponible. Utilisez MoonPay ou USDT direct.",
        percentSuffix: "Collecté",
        ackTitle: "💎 Initiateurs de la campagne · Petits gestes grands effets",
        contactEmailLabel: "📧 Email de contact :",

        ackName1: "Yuxuan Chen", ackJob1: "Ingénieur logiciel", ackMotto1: "« Le code change le monde, la gentillesse aussi. »",
        ackName2: "Yutong Lin", ackJob2: "Vétérinaire", ackMotto2: "« Chaque suture est une renaissance. »",
        ackName3: "Haoze Wang", ackJob3: "Étudiant bénévole", ackMotto3: "« La passion jeune doit couler là où on a le plus besoin. »",
        ackName4: "Simin Zhao", ackJob4: "Comptable", ackMotto4: "« Chaque don est une confiance, doit être clair. »",
        ackName5: "Ziang Liu", ackJob5: "Responsable logistique", ackMotto5: "« Chaque kilo de croquettes arrive à l'heure. »",
        ackName6: "Xiaoqi Zhou", ackJob6: "Designer graphique", ackMotto6: "« Le design peut être doux, la vie doit être forte. »",
        ackName7: "Yichen Lin", ackJob7: "Photographe indépendant", ackMotto7: "« Après avoir pris des photos, j'essuie les yeux des chiens. »",
        ackName8: "Hangxuan Chen", ackJob8: "Barista", ackMotto8: "« Après le travail, j'utilise le marc de café pour désodoriser les chenils. »",
        ackName9: "Zirui He", ackJob9: "Concepteur de jeux", ackMotto9: "« Concevoir des mondes virtuels, aussi vouloir sauver des vies réelles. »",
        ackName10: "Cheng Zhou", ackJob10: "Coach sportif", ackMotto10: "« En plus de soulever de la fonte, donnez un peu de force aux chiens errants. »",
        ackName11: "Yiming Lu", ackJob11: "Boulanger", ackMotto11: "« Les mains qui pétrissent la pâte peuvent aussi brosser les poils des chiens. »",
        ackName12: "Yifan Wu", ackJob12: "Animateur", ackMotto12: "« Chaque image est lente, mais sauver des chiens ne peut pas être lent. »",
        ackName13: "Wanqing Su", ackJob13: "Fleuriste", ackMotto13: "« Envelopper des bouquets, aussi panser les blessures des chiens errants. »",
        ackName14: "Wanning Xia", ackJob14: "Illustratrice", ackMotto14: "« La palette est couleur, le refuge est chaleur. »",
        ackName15: "Youran Song", ackJob15: "Planificatrice de marque", ackMotto15: "« Racontez une bonne histoire pour les chiens errants, alors ils pourront être adoptés. »"
    },
    de: {
        badgeTemp: "⚠️ Notfallrettung",
        badgeGroup: "Basisgruppe · Keine staatlichen Gelder",
        mainTitle: "Winterhilfe: Spenden für verletzte streunende Hunde",
        p1: "📸 Hunde warten auf Behandlung",
        p2: "📸 Hungernde und frierende Streuner",
        p3: "📸 Alltag im Tierheim",
        storyTitle: "🐾 Der harte Kampf der Streunerhunde",
        storyP1: "In China gibt es Millionen streunender Hunde. Die meisten wurden von ihren Besitzern ausgesetzt oder auf der Straße geboren. Sie haben keine feste Nahrungsquelle, wühlen in Mülltonnen und keinen Schutz vor eisigen Wintern oder heißen Sommern. Viele erleiden Frakturen, Hautkrankheiten oder Augeninfektionen durch Unfälle oder Misshandlung. Ohne Tierschutzgesetz erhalten sie keine staatliche Hilfe.",
        storyP2: "Wir sind eine Gruppe junger Initiatoren dieser Spendenaktion. Wir nutzen unsere Freizeit, um Tierärzte zu kontaktieren, geeignete Tierheime zu finden und Freiwilligenschichten zu organisieren. Wir tragen nicht alle Kosten selbst. Stattdessen sammeln wir durch diese Kampagne Spenden von hilfsbereiten Menschen für die medizinische Behandlung und das Futter der streunenden Hunde. Wir sorgen dafür, dass jede Spende transparent ist und bei den Hunden ankommt, die sie am dringendsten benötigen.",
        storyP3: "Jeder gerettete Hund erhält medizinische Behandlung, Sterilisation, Impfungen, und dann versuchen wir, ein liebevolles Zuhause für ihn zu finden. Ihre Spende, egal wie hoch, fließt direkt in Medikamente, Hundefutter und Operationskosten. Wir veröffentlichen regelmäßig Finanzberichte in sozialen Medien. Bitte helfen Sie diesen armen Seelen zu einer zweiten Chance.",
        useT1: "🍖 Tägliches Futter",
        useP1: "5 $ kaufen eine Tüte Trockenfutter, die einen mittelgroßen Hund eine Woche lang ernährt.",
        useT2: "🏥 Medizinische Versorgung",
        useP2: "Die durchschnittlichen Behandlungskosten pro verletztem Hund liegen bei etwa 10 $. 2 $ kaufen eine Entwurmungstablette.",
        allocTitle: "📊 Mittelverwendung",
        alloc1: "45% Medizinische Behandlung & Medikamente",
        alloc2: "30% Hundefutter & Ernährung",
        alloc3: "15% Tierheimwartung & Heizung",
        alloc4: "10% Transportkosten",
        targetLbl: "On-Chain-Ziel: 4.500 USDT",
        liveStatus: "🔴 Blockchain-synchronisiert – Jede Transaktion öffentlich",
        payTitle: "🔪 Helfen Sie Streunerhunden",
        paySub: "Füllen Sie das Formular aus, um eine sichere Zahlungsmethode zu wählen. Wir veröffentlichen regelmäßig Berichte über die Mittelverwendung.",
        lblEmail: "Ihre E-Mail (für Updates zu Rettungen)",
        lblNotes: "Nachricht für die Hunde",
        btnMoonPay: "Über sicheres Gateway spenden",
        btnDirect: "Ich habe USDT überwiesen",
        directLbl: "Senden Sie USDT (ERC20) direkt an unsere Wallet",
        wechatErr: "WeChat Pay nicht verfügbar. Bitte nutzen Sie MoonPay oder direkte USDT.",
        percentSuffix: "Gesammelt",
        ackTitle: "💎 Kampagneninitiatoren · Gemeinsam stark",
        contactEmailLabel: "📧 Kontakt-E-Mail:",

        ackName1: "Yuxuan Chen", ackJob1: "Softwareentwickler", ackMotto1: "« Code verändert die Welt, Freundlichkeit auch. »",
        ackName2: "Yutong Lin", ackJob2: "Tierärztin", ackMotto2: "« Jede Naht ist eine Wiedergeburt. »",
        ackName3: "Haoze Wang", ackJob3: "Studentischer Freiwilliger", ackMotto3: "« Junge Leidenschaft sollte dorthin fließen, wo sie am nötigsten ist. »",
        ackName4: "Simin Zhao", ackJob4: "Buchhalterin", ackMotto4: "« Jede Spende ist Vertrauen, muss klar sein. »",
        ackName5: "Ziang Liu", ackJob5: "Logistikleiter", ackMotto5: "« Jedes Kilo Hundefutter kommt pünktlich an. »",
        ackName6: "Xiaoqi Zhou", ackJob6: "Grafikdesignerin", ackMotto6: "« Design kann sanft sein, Leben muss stark sein. »",
        ackName7: "Yichen Lin", ackJob7: "Freiberuflicher Fotograf", ackMotto7: "« Nach dem Fotografieren wische ich den Hunden die Augen. »",
        ackName8: "Hangxuan Chen", ackJob8: "Barista", ackMotto8: "« Nach der Arbeit benutze ich Kaffeesatz, um die Hundezwinger zu desodorieren. »",
        ackName9: "Zirui He", ackJob9: "Spieleentwickler", ackMotto9: "« Virtuelle Welten entwerfen, auch echte Leben retten wollen. »",
        ackName10: "Cheng Zhou", ackJob10: "Fitnesstrainer", ackMotto10: "« Neben dem Eisenheben, gib den streunenden Hunden etwas Kraft. »",
        ackName11: "Yiming Lu", ackJob11: "Bäcker", ackMotto11: "« Hände, die Teig kneten, können auch Hundehaare bürsten. »",
        ackName12: "Yifan Wu", ackJob12: "Animator", ackMotto12: "« Jeder Frame ist langsam, aber Hunde retten kann nicht langsam sein. »",
        ackName13: "Wanqing Su", ackJob13: "Floristin", ackMotto13: "« Blumensträuße binden, auch Wunden streunender Hunde verbinden. »",
        ackName14: "Wanning Xia", ackJob14: "Illustratorin", ackMotto14: "« Die Palette ist Farbe, das Tierheim ist Wärme. »",
        ackName15: "Youran Song", ackJob15: "Markenplanerin", ackMotto15: "« Erzähle eine gute Geschichte für streunende Hunde, dann können sie adoptiert werden. »"
    },
    ru: {
        badgeTemp: "⚠️ Экстренное спасение",
        badgeGroup: "Низовая группа · Без госфинансирования",
        mainTitle: "Зимняя помощь: сбор средств для раненых бездомных собак",
        p1: "📸 Собаки в ожидании лечения",
        p2: "📸 Голодные и замёрзшие бродяги",
        p3: "📸 Будни приюта",
        storyTitle: "🐾 Тяжёлая борьба бездомных собак",
        storyP1: "В Китае миллионы бездомных собак. Большинство были брошены хозяевами или родились на улице. У них нет постоянного источника пищи, они роются в мусорных баках, нет укрытия от ледяной зимы или палящего лета. Многие страдают от переломов, кожных заболеваний или глазных инфекций из-за несчастных случаев или жестокого обращения. Без закона о защите животных они не получают государственной помощи.",
        storyP2: "Мы — группа молодых инициаторов этой кампании по сбору средств. Мы используем свободное время, чтобы связаться с ветеринарами, найти подходящие приюты и организовать волонтёрские смены. Мы не несём все расходы сами. Вместо этого, запуская эту кампанию, мы собираем средства у неравнодушных людей на лечение и корм бездомных собак. Мы следим за тем, чтобы каждое пожертвование было прозрачным и доходило до собак, которые больше всего в этом нуждаются.",
        storyP3: "Каждая спасённая собака получает медицинскую помощь, стерилизацию, прививки, а затем мы пытаемся найти ей любящий дом. Ваше пожертвование, независимо от размера, пойдёт напрямую на лекарства, корм и операции. Мы регулярно публикуем финансовые отчёты в соцсетях. Пожалуйста, помогите этим бедным душам получить второй шанс.",
        useT1: "🍖 Ежедневный корм",
        useP1: "5 долларов могут купить пакет сухого корма, которого хватит средней собаке на неделю.",
        useT2: "🏥 Медицинская помощь",
        useP2: "Средняя стоимость лечения одной раненой собаки составляет около 10 долларов. 2 доллара могут купить таблетку от глистов.",
        allocTitle: "📊 Распределение средств",
        alloc1: "45% Медицинское лечение и лекарства",
        alloc2: "30% Корм и питание",
        alloc3: "15% Обслуживание приюта и отопление",
        alloc4: "10% Транспортные расходы",
        targetLbl: "Ончейн-цель: 4 500 USDT",
        liveStatus: "🔴 Синхронизировано с блокчейном – все транзакции публичны",
        payTitle: "🔪 Помогите бездомным собакам",
        paySub: "Заполните форму, чтобы выбрать безопасный способ оплаты. Мы будем регулярно публиковать отчёты об использовании средств.",
        lblEmail: "Ваш email (для получения новостей о спасении)",
        lblNotes: "Сообщение для собак",
        btnMoonPay: "Пожертвовать через безопасный шлюз",
        btnDirect: "Я перевёл USDT",
        directLbl: "Отправьте USDT (ERC20) напрямую в наш кошелёк",
        wechatErr: "WeChat Pay недоступен. Используйте MoonPay или прямой USDT.",
        percentSuffix: "Собрано",
        ackTitle: "💎 Инициаторы кампании · По капле море",
        contactEmailLabel: "📧 Контактный email:",

        ackName1: "Yuxuan Chen", ackJob1: "Инженер-программист", ackMotto1: "« Код меняет мир, доброта — тоже. »",
        ackName2: "Yutong Lin", ackJob2: "Ветеринар", ackMotto2: "« Каждый шов — это возрождение. »",
        ackName3: "Haoze Wang", ackJob3: "Студент-волонтёр", ackMotto3: "« Молодая страсть должна течь туда, где она нужнее всего. »",
        ackName4: "Simin Zhao", ackJob4: "Бухгалтер", ackMotto4: "« Каждое пожертвование — это доверие, оно должно быть прозрачным. »",
        ackName5: "Ziang Liu", ackJob5: "Руководитель логистики", ackMotto5: "« Каждый килограмм корма прибывает вовремя. »",
        ackName6: "Xiaoqi Zhou", ackJob6: "Графический дизайнер", ackMotto6: "« Дизайн может быть нежным, жизнь должна быть сильной. »",
        ackName7: "Yichen Lin", ackJob7: "Фриланс-фотограф", ackMotto7: "« После съёмки вытираю глаза собакам. »",
        ackName8: "Hangxuan Chen", ackJob8: "Бариста", ackMotto8: "« После работы использую кофейную гущу, чтобы убрать запах из будок. »",
        ackName9: "Zirui He", ackJob9: "Гейм-дизайнер", ackMotto9: "« Создавая виртуальные миры, хочу спасать реальные жизни. »",
        ackName10: "Cheng Zhou", ackJob10: "Фитнес-тренер", ackMotto10: "« Кроме поднятия тяжестей, дайте немного сил бездомным собакам. »",
        ackName11: "Yiming Lu", ackJob11: "Пекарь", ackMotto11: "« Руки, которые месят тесто, могут и расчёсывать шерсть собак. »",
        ackName12: "Yifan Wu", ackJob12: "Аниматор", ackMotto12: "« Каждый кадр медленный, но спасение собак не может быть медленным. »",
        ackName13: "Wanqing Su", ackJob13: "Флорист", ackMotto13: "« Обёртывая букеты, также перевязываю раны бездомных собак. »",
        ackName14: "Wanning Xia", ackJob14: "Иллюстратор", ackMotto14: "« Палитра — это цвет, приют — это тепло. »",
        ackName15: "Youran Song", ackJob15: "Бренд-планер", ackMotto15: "« Расскажите хорошую историю для бездомных собак, тогда их смогут усыновить. »"
    },
    ar: {
        badgeTemp: "⚠️ إنقاذ طارئ",
        badgeGroup: "مجموعة شعبية · بدون تمويل حكومي",
        mainTitle: "إغاثة الشتاء: جمع تبرعات للكلاب الضالة المصابة",
        p1: "📸 كلاب تنتظر العلاج",
        p2: "📸 كلاب ضالة جائعة وباردة",
        p3: "📸 الحياة اليومية في الملجأ",
        storyTitle: "🐾 المعاناة القاسية للكلاب الضالة",
        storyP1: "في الصين، هناك ملايين الكلاب الضالة. معظمها تم التخلي عنها من قبل أصحابها أو ولدت في الشوارع. ليس لديها مصدر غذاء ثابت، فتفتش في صناديق القمامة، ولا مأوى لها من فصول الشتاء المتجمدة أو الصيف الحارق. يعاني الكثير من الكسور والأمراض الجلدية أو التهابات العين بسبب الحوادث أو سوء المعاملة. بدون قانون حماية الحيوان، لا تحصل على أي مساعدة حكومية.",
        storyP2: "نحن مجموعة من الشباب المبادرين لهذه الحملة لجمع التبرعات. نستخدم وقت فراغنا للتواصل مع الأطباء البيطريين، وإيجاد ملاجئ مناسبة، وتنظيم جداول المتطوعين. نحن لا نتحمل جميع التكاليف بأنفسنا. بدلاً من ذلك، من خلال إطلاق هذه الحملة، نجمع الأموال من الأشخاص المهتمين للعلاج الطبي والغذاء للكلاب الضالة. نضمن أن كل تبرع يكون شفافاً ويصل إلى الكلاب الأكثر احتياجاً.",
        storyP3: "كل كلب ننقذه يتلقى رعاية طبية وتعقيمًا وتطعيمات، ثم نحاول إيجاد منزل محب له. تبرعك، مهما كان حجمه، سيذهب مباشرة إلى الأدوية وطعام الكلاب وتكاليف العمليات. ننشر تقارير مالية بانتظام على وسائل التواصل الاجتماعي. الرجاء مساعدة هذه الأرواح المسكينة في الحصول على فرصة ثانية.",
        useT1: "🍖 الطعام اليومي",
        useP1: "5 دولارات يمكن أن تشتري كيسًا من الطعام الجاف يكفي كلبًا متوسط الحجم لمدة أسبوع.",
        useT2: "🏥 الرعاية الطبية",
        useP2: "متوسط تكلفة العلاج لكل كلب مصاب حوالي 10 دولارات. دولاران يمكن أن يشتريا حبة ديدان.",
        allocTitle: "📊 توزيع الأموال",
        alloc1: "45% العلاج الطبي والأدوية",
        alloc2: "30% طعام الكلاب والتغذية",
        alloc3: "15% صيانة الملجأ والتدفئة",
        alloc4: "10% تكاليف النقل",
        targetLbl: "هدف على السلسلة: 4,500 USDT",
        liveStatus: "🔴 متزامن مع البلوكشين – كل معاملة علنية",
        payTitle: "🔪 ساعد الكلاب الضالة",
        paySub: "املأ النموذج لاختيار طريقة دفع آمنة. سننشر تقارير استخدام الأموال بانتظام.",
        lblEmail: "بريدك الإلكتروني (لتلقي تحديثات الإنقاذ)",
        lblNotes: "رسالة للكلاب",
        btnMoonPay: "تبرع عبر بوابة آمنة",
        btnDirect: "لقد حولت USDT",
        directLbl: "أرسل USDT (ERC20) مباشرة إلى محفظتنا",
        wechatErr: "WeChat Pay غير متاح. استخدم MoonPay أو USDT مباشرًا.",
        percentSuffix: "تم التجميع",
        ackTitle: "💎 مبادرون الحملة · نقطة فوق نقطة بحر",
        contactEmailLabel: "📧 البريد الإلكتروني للاتصال:",

        ackName1: "Yuxuan Chen", ackJob1: "مهندس برمجيات", ackMotto1: "« البرمجيات تغير العالم، وكذلك اللطف. »",
        ackName2: "Yutong Lin", ackJob2: "طبيب بيطري", ackMotto2: "« كل غرزة هي ولادة جديدة. »",
        ackName3: "Haoze Wang", ackJob3: "متطوع جامعي", ackMotto3: "« يجب أن تتدفق الحماسة الشبابية حيث تشتد الحاجة إليها. »",
        ackName4: "Simin Zhao", ackJob4: "محاسب", ackMotto4: "« كل تبرع هو ثقة، يجب أن يكون شفافًا. »",
        ackName5: "Ziang Liu", ackJob5: "مدير سلسلة التوريد", ackMotto5: "« كل كيلوغرام من طعام الكلاب يصل في الوقت المحدد. »",
        ackName6: "Xiaoqi Zhou", ackJob6: "مصمم جرافيك", ackMotto6: "« التصميم يمكن أن يكون لطيفًا، ولكن الحياة يجب أن تكون قوية. »",
        ackName7: "Yichen Lin", ackJob7: "مصور مستقل", ackMotto7: "« بعد التقاط الصور، أمسح عيون الكلاب. »",
        ackName8: "Hangxuan Chen", ackJob8: "باريستا", ackMotto8: "« بعد العمل، أستخدم بقايا القهوة لإزالة الروائح من بيوت الكلاب. »",
        ackName9: "Zirui He", ackJob9: "مصمم ألعاب", ackMotto9: "« تصميم عوالم افتراضية، أريد أيضًا إنقاذ أرواح حقيقية. »",
        ackName10: "Cheng Zhou", ackJob10: "مدرب لياقة بدنية", ackMotto10: "« بالإضافة إلى رفع الأثقال، أعط القليل من القوة للكلاب الضالة. »",
        ackName11: "Yiming Lu", ackJob11: "خباز", ackMotto11: "« الأيدي التي تعجن العجين يمكنها أيضًا تمشيط فراء الكلاب. »",
        ackName12: "Yifan Wu", ackJob12: "رسام رسوم متحركة", ackMotto12: "« كل إطار بطيء، لكن إنقاذ الكلاب لا يمكن أن يكون بطيئًا. »",
        ackName13: "Wanqing Su", ackJob13: "بائعة زهور", ackMotto13: "« تغليف باقات الزهور، أيضًا تضميد جروح الكلاب الضالة. »",
        ackName14: "Wanning Xia", ackJob14: "رسامة توضيحية", ackMotto14: "« اللوحة هي ألوان، الملجأ هو دفء. »",
        ackName15: "Youran Song", ackJob15: "مخططة العلامات التجارية", ackMotto15: "« اروِ قصة جيدة للكلاب الضالة، عندها يمكن تبنّيها. »"
    }
};